# Tap Sources
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "siderolabs/tap"

# CLI Tools
brew "act"
brew "bat"
brew "curl"
brew "doctl"
brew "exiftool"
brew "ffmpeg"
brew "fzf"
brew "git-lfs"
brew "go"
brew "kubernetes-cli"
brew "mas"
brew "md5sha1sum"
brew "mosh"
brew "mypy"
brew "node"
brew "prettier"
brew "pyenv"
brew "python@3.11"
brew "redis"
brew "ripgrep"
brew "talosctl"
brew "terminal-notifier"
brew "tree"
brew "universal-ctags"
brew "vim"
brew "yarn"
brew "zsh-syntax-highlighting"

# General Applications
cask "1password"
cask "1password-cli"
cask "numi"
cask "slack"
cask "spotify"
cask "zoom"

# Peripheral Applications
cask "uhk-agent"

# Coding Applications
cask "db-browser-for-sqlite"
cask "docker"
cask "flutter"
cask "github"
cask "ghostty"
cask "multipass"
cask "balenaetcher"

# System Helpers
cask "hiddenbar"
cask "keepingyouawake"
cask "openinterminal-lite"
cask "tunnelblick"
cask "rectangle"

# Fonts
cask "font-hack"
