name: install from branch

on:
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13]
        include:
          - os: ubuntu-22.04
            variant: linux
          - os: macos-13
            variant: darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Remove gitconfig
        run: |
          if [ -f ~/.gitconfig ]; then
            rm ~/.gitconfig
          fi

      - name: Install script
        run: ./install
