name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13]
        include:
          - os: ubuntu-22.04
            variant: linux
          - os: macos-13
            variant: darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Remove gitconfig
        run: |
          if [ -f ~/.gitconfig ]; then
            rm ~/.gitconfig
          fi

      - name: Cache brew dependencies
        id: cache-dependencies
        if: runner.os == 'macOS'
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/Cellar
            /usr/local/Homebrew
            ~/Library/Caches/Homebrew
          key: ${{ runner.os }}-brew-${{ hashFiles('**/Brewfile') }}
          restore-keys: |
            ${{ runner.os }}-brew-

      - name: Install Homebrew packages
        if: runner.os == 'macOS' && steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          brew bundle

      - name: Install script
        run: ./install
